### ISSUE TITLE
gb test does not print output for tests in package main (?)

### ISSUE THREAD

**Issue by liamstask** [constabulary/gb#448] opened 2015-11-11 01:10 UTC
Not sure if this is actually the issue, but i'm seeing the following behavior currently with 0.3.1:
* `gb test` on a non-main package runs tests with output as expected
* `gb test` on a main package results in just project name being printed
* cd into folder with source files in main package, and `go test` runs tests with output as expected

**Comment by davecheney** [comment] 2015-11-11 01:15
Thanks for the issue report. Due to an annoying bug `gb test -v` won't turn
on any sort of verbose output.

I cannot reproduce your problem (I added a test that slept for 10 seconds,
and the output of the package name was delayed by the expected amount of
time)
```
lucky(~/src/github.com/constabulary/gb/cmd) % gb test -v
github.com/constabulary/gb/cmd/gb-vendor
github.com/constabulary/gb/cmd
# github.com/constabulary/gb/cmd/gb
=== RUN   TestUnion
--- PASS: TestUnion (0.00s)
=== RUN   TestIntersection
--- PASS: TestIntersection (0.00s)
=== RUN   TestDifference
--- PASS: TestDifference (0.00s)
=== RUN   TestContains
--- PASS: TestContains (0.00s)
=== RUN   TestSleep
sleeping for 10 seconds
--- FAIL: TestSleep (10.00s)
=== RUN   TestTestFlagsPreParse
--- PASS: TestTestFlagsPreParse (0.00s)
=== RUN   TestTestFlags
--- PASS: TestTestFlags (0.00s)
FAIL
FATAL: command "test" failed: exit status 1
```

Is the source of your code online somewhere ?

**Comment by liamstask** [comment] 2015-11-11 01:29
it's a bit of code i was sketching, and don't have up online anywhere, but this minimal case (https://gist.github.com/liamstask/87d2e90958de030ecbaa) that shows this behavior on my machine, where the path to these files is `mymain/src/mymain`.

**Comment by davecheney** [comment] 2015-11-11 01:30
ok, i need to fix -v to turn on debugging for tests, then i'll get back to
you

**Comment by davecheney** [comment] 2015-11-11 09:42
Hello, 

Could you please make sure you have #450 and try the following
```
go get -u github.com/constabulary/gb/...
env DEBUG=. gb test $whatever you were doing before
```
And paste or attach all the output.

It should be straight forward to figure it out from there.

**Comment by liamstask** [comment] 2015-11-11 18:00
thanks. output:
```
drungus:mymain liam$ env DEBUG=. gb test -v
2015/11/11 09:57:11 debug.go:27: project root "/Users/liam/code/github/mymain"
2015/11/11 09:57:11 debug.go:27: matchPackages: /Users/liam/code/github/mymain/src ...
2015/11/11 09:57:11 debug.go:27: args: [mymain]
2015/11/11 09:57:11 debug.go:27: loadTestFuncs: [main_test.go], []
2015/11/11 09:57:11 debug.go:27: cd /Users/liam/code/github/mymain/src/mymain; [/usr/local/Cellar/go/1.5.1/libexec/pkg/tool/darwin_amd64/compile -p mymain -pack -o /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028/mymain/_test/mymain.a -I /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028 -I /Users/liam/code/github/mymain/pkg/darwin-amd64 -complete main.go main_test.go]
2015/11/11 09:57:11 debug.go:27: cd /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028/mymain/_test; [/usr/local/Cellar/go/1.5.1/libexec/pkg/tool/darwin_amd64/compile -p mymain/testmain -pack -o /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028/mymain/testmain/_test/mymain/testmain/main.a -I /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028/mymain/_test -I /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028 -I /Users/liam/code/github/mymain/pkg/darwin-amd64 -complete _testmain.go]
2015/11/11 09:57:11 debug.go:27: cd .; [/usr/local/Cellar/go/1.5.1/libexec/pkg/tool/darwin_amd64/link -o /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028/mymain/testmain/_test/mymain.test -L /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028/mymain/_test -L /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028 -L /Users/liam/code/github/mymain/pkg/darwin-amd64 -buildmode exe /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028/mymain/testmain/_test/mymain/testmain/main.a]
mymain
2015/11/11 09:57:11 debug.go:27: test duration: 473.321677ms map[gc:50.653096ms link:414.45928ms]
2015/11/11 09:57:11 debug.go:27: removing work directory: /var/folders/fv/trs94mf53bd7s41vdxkdbpjr0000gn/T/gb541435028
```

**Comment by layered-esell** [comment] 2015-11-12 15:34
just a +1 that we are also seeing this issue on one of our projects.

**Comment by davecheney** [comment] 2015-11-12 19:56
@layered-esell could you please follow the same procedure as above and include the output. Thanks

**Comment by layered-esell** [comment] 2015-11-12 23:49
Sure thing, here you go:

```
$ env DEBUG=. gb test
2015/11/12 16:46:46 debug.go:27: project root "/Users/eujon/goproj/adt"
2015/11/12 16:46:46 debug.go:27: matchPackages: /Users/eujon/goproj/adt/src ...
2015/11/12 16:46:46 debug.go:27: args: [github.com/radiantiq/adt]
2015/11/12 16:46:46 debug.go:27: loadTestFuncs: [main_test.go], []
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/vendor/src/github.com/julienschmidt/httprouter; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/julienschmidt/httprouter -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/julienschmidt/httprouter.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete path.go router.go tree.go]
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/vendor/src/github.com/satori/go.uuid; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/satori/go.uuid -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/satori/go.uuid.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete uuid.go]
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/vendor/src/github.com/oxtoacart/bpool; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/oxtoacart/bpool -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/oxtoacart/bpool.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete bpool.go bufferpool.go bytepool.go sizedbufferpool.go]
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/vendor/src/github.com/plimble/utils/pool; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/plimble/utils/pool -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/plimble/utils/pool.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete buffer.go byte.go]
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/vendor/src/github.com/philhofer/fwd; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/philhofer/fwd -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/philhofer/fwd.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete reader.go writer.go writer_unsafe.go]
2015/11/12 16:46:46 debug.go:27: copyfile(dst: /Users/eujon/goproj/adt/pkg/darwin-amd64/github.com/plimble/utils/pool.a, src: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/plimble/utils/pool.a)
github.com/plimble/utils/pool
2015/11/12 16:46:46 debug.go:27: copyfile(dst: /Users/eujon/goproj/adt/pkg/darwin-amd64/github.com/oxtoacart/bpool.a, src: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/oxtoacart/bpool.a)
github.com/oxtoacart/bpool
2015/11/12 16:46:46 debug.go:27: copyfile(dst: /Users/eujon/goproj/adt/pkg/darwin-amd64/github.com/philhofer/fwd.a, src: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/philhofer/fwd.a)
github.com/philhofer/fwd
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/vendor/src/github.com/tinylib/msgp/msgp; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/tinylib/msgp/msgp -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/tinylib/msgp/msgp.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete advise_other.go circular.go defs.go edit.go elsize.go errors.go extension.go file.go integers.go json.go json_bytes.go number.go read.go read_bytes.go size.go unsafe.go write.go write_bytes.go]
2015/11/12 16:46:46 debug.go:27: copyfile(dst: /Users/eujon/goproj/adt/pkg/darwin-amd64/github.com/satori/go.uuid.a, src: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/satori/go.uuid.a)
github.com/satori/go.uuid
2015/11/12 16:46:46 debug.go:27: copyfile(dst: /Users/eujon/goproj/adt/pkg/darwin-amd64/github.com/julienschmidt/httprouter.a, src: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/julienschmidt/httprouter.a)
github.com/julienschmidt/httprouter
2015/11/12 16:46:46 debug.go:27: copyfile(dst: /Users/eujon/goproj/adt/pkg/darwin-amd64/github.com/tinylib/msgp/msgp.a, src: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/tinylib/msgp/msgp.a)
github.com/tinylib/msgp/msgp
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/vendor/src/github.com/plimble/sessions; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/plimble/sessions -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/plimble/sessions.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete manager.go session.go session_gen.go sessions.go store.go utils.go]
2015/11/12 16:46:46 debug.go:27: copyfile(dst: /Users/eujon/goproj/adt/pkg/darwin-amd64/github.com/plimble/sessions.a, src: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/plimble/sessions.a)
github.com/plimble/sessions
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/vendor/src/github.com/plimble/ace; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/plimble/ace -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/plimble/ace.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete ace.go context.go logger.go recovery.go response_writer.go router.go session.go template.go utils.go]
2015/11/12 16:46:46 debug.go:27: copyfile(dst: /Users/eujon/goproj/adt/pkg/darwin-amd64/github.com/plimble/ace.a, src: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/plimble/ace.a)
github.com/plimble/ace
2015/11/12 16:46:46 debug.go:27: cd /Users/eujon/goproj/adt/src/github.com/radiantiq/adt; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/radiantiq/adt -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/radiantiq/adt/_test/github.com/radiantiq/adt.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete main.go main_test.go]
2015/11/12 16:46:47 debug.go:27: cd /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/radiantiq/adt/_test/github.com/radiantiq; [/usr/local/go/pkg/tool/darwin_amd64/compile -p github.com/radiantiq/adt/testmain -pack -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/radiantiq/adt/testmain/_test/github.com/radiantiq/adt/testmain/main.a -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/radiantiq/adt/_test -I /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -I /Users/eujon/goproj/adt/pkg/darwin-amd64 -complete _testmain.go]
2015/11/12 16:46:47 debug.go:27: cd .; [/usr/local/go/pkg/tool/darwin_amd64/link -o /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/radiantiq/adt/testmain/_test/adt.test -L /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/radiantiq/adt/_test -L /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253 -L /Users/eujon/goproj/adt/pkg/darwin-amd64 -buildmode exe /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253/github.com/radiantiq/adt/testmain/_test/github.com/radiantiq/adt/testmain/main.a]
github.com/radiantiq/adt
2015/11/12 16:46:59 debug.go:27: test duration: 13.378284986s map[gc:1.362294412s link:1.255222676s]
2015/11/12 16:46:59 debug.go:27: removing work directory: /var/folders/2t/ykkkgjtd3lx3ncj8plkhlzs00000gn/T/gb879092253
```

**Comment by mowings** [comment] 2015-11-21 16:41
+1 on this -- same issue here.  Even if I throw a fmt.Println into the top of the test I see nothing. This is on  a linux amd64 container. Note that in this case, GOPATH and the project directory are the same

**Comment by Gouthamve** [comment] 2015-11-22 05:49
+1 I am seeing this too. Its kindof annoying.

**Comment by davecheney** [comment] 2015-11-22 05:51
@mowings, could you please follow the same procedure described about,
you'll have to export GB_DEBUG=. if you're using a recent version of gb to
get the debugging output.

**Comment by Gouthamve** [comment] 2015-11-22 05:59
Sorry for not giving the debug output.
Here is mine. Ran ```gb test worker``` with DEBUG=.

```
2015/11/22 11:24:08 debug.go:27: project root "/Users/goutham/CrazyAnalytics/EventServer"
2015/11/22 11:24:08 debug.go:27: args: [worker]
2015/11/22 11:24:08 debug.go:27: loadTestFuncs: [handlers_test.go], []
2015/11/22 11:24:08 debug.go:27: cd /Users/goutham/CrazyAnalytics/EventServer/src/worker; [/usr/local/go/pkg/tool/darwin_amd64/compile -p worker -pack -o /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674/worker/_test/worker.a -I /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674 -I /Users/goutham/CrazyAnalytics/EventServer/pkg/darwin-amd64 -complete fsm.go handlers.go main.go handlers_test.go]
2015/11/22 11:24:08 debug.go:27: cd /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674/worker/_test; [/usr/local/go/pkg/tool/darwin_amd64/compile -p worker/testmain -pack -o /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674/worker/testmain/_test/worker/testmain/main.a -I /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674/worker/_test -I /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674 -I /Users/goutham/CrazyAnalytics/EventServer/pkg/darwin-amd64 -complete _testmain.go]
2015/11/22 11:24:08 debug.go:27: cd .; [/usr/local/go/pkg/tool/darwin_amd64/link -o /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674/worker/testmain/_test/worker.test -L /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674/worker/_test -L /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674 -L /Users/goutham/CrazyAnalytics/EventServer/pkg/darwin-amd64 -buildmode exe /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674/worker/testmain/_test/worker/testmain/main.a]
worker
2015/11/22 11:24:10 debug.go:27: test duration: 1.993872749s map[gc:425.194424ms link:1.162601796s]
2015/11/22 11:24:10 debug.go:27: removing work directory: /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb699021674
```
```GB_DEBUG``` is not working for me only ```DEBUG=.``` is. I just ran go get -u.

Also, I am resorting to this:
```
export GB_PROJECT_DIR="/Users/goutham/CrazyAnalytics/EventServer"
export GOPATH=$GB_PROJECT_DIR:$GB_PROJECT_DIR/vendor
go test worker
```

**Comment by davecheney** [comment] 2015-11-22 06:01
Sorry, yes, DEBUG is the correct env bar

**Comment by mowings** [comment] 2015-11-25 23:23
Here's mine:

````
vagrant@pixelpipe:/vagrant/src/pixelpipe$ DEBUG=. gb test -v
2015/11/25 17:20:17 debug.go:27: project root "/vagrant"
2015/11/25 17:20:17 debug.go:27: matchPackages: /vagrant/src pixelpipe/...
2015/11/25 17:20:17 debug.go:27: args: [pixelpipe]
2015/11/25 17:20:17 debug.go:27: loadTestFuncs: [environment_test.go job_test.go queue_test.go], []
2015/11/25 17:20:17 debug.go:27: cd /vagrant/src/pixelpipe; [/usr/local/go/pkg/tool/linux_amd64/compile -p pixelpipe -pack -o /tmp/gb946842890/pixelpipe/_test/pixelpipe.a -I /tmp/gb946842890 -I /vagrant/pkg/linux-amd64 -complete environment.go farm.go job.go main.go queue.go state.go wait_job_event.go environment_test.go job_test.go queue_test.go]
2015/11/25 17:20:18 debug.go:27: cd /tmp/gb946842890/pixelpipe/_test; [/usr/local/go/pkg/tool/linux_amd64/compile -p pixelpipe/testmain -pack -o /tmp/gb946842890/pixelpipe/testmain/_test/pixelpipe/testmain/main.a -I /tmp/gb946842890/pixelpipe/_test -I /tmp/gb946842890 -I /vagrant/pkg/linux-amd64 -complete _testmain.go]
2015/11/25 17:20:18 debug.go:27: cd .; [/usr/local/go/pkg/tool/linux_amd64/link -o /tmp/gb946842890/pixelpipe/testmain/_test/pixelpipe.test -L /tmp/gb946842890/pixelpipe/_test -L /tmp/gb946842890 -L /vagrant/pkg/linux-amd64 -buildmode exe /tmp/gb946842890/pixelpipe/testmain/_test/pixelpipe/testmain/main.a]
pixelpipe
2015/11/25 17:20:28 debug.go:27: test duration: 10.446222817s map[link:4.051579067s gc:1.067939472s]
2015/11/25 17:20:28 debug.go:27: removing work directory: /tmp/gb946842890
````

**Comment by davecheney** [comment] 2015-11-25 23:31
Thanks. What I see happening is building and linking the test binary
happens fine, but then it does not schedule the run of the binary.

**Comment by davecheney** [comment] 2015-11-26 10:37
I'm working on this now. I'll have a PR to test shortly.

**Comment by davecheney** [comment] 2015-11-26 11:06
@liamstask @mowings @Gouthamve I'm going to submit #463 and release 0.3.2, I hope that this fixes the problem, or at least makes it clear what is going on.

**Comment by Gouthamve** [comment] 2015-11-26 11:32
@davecheney I am still not able to test. While a failure is printing, I am not able to see the success, I don't know if its the expected behaviour. When successful, only the package name is printing.

DEBUG=. output:
```
2015/11/26 17:01:20 cmd.go:88: project root "/Users/goutham/CrazyAnalytics/EventServer"
2015/11/26 17:01:20 main.go:134: args: [worker]
2015/11/26 17:01:20 gotest.go:95: loadTestFuncs: [handlers_test.go], []
2015/11/26 17:01:20 context.go:221: cd /Users/goutham/CrazyAnalytics/EventServer/src/worker; [/usr/local/go/pkg/tool/darwin_amd64/compile -p worker -pack -o /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432/worker/_test/worker.a -I /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432 -I /Users/goutham/CrazyAnalytics/EventServer/pkg/darwin-amd64 -complete fsm.go handlers.go main.go handlers_test.go]
2015/11/26 17:01:21 context.go:221: cd /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432/worker/_test; [/usr/local/go/pkg/tool/darwin_amd64/compile -p worker/testmain -pack -o /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432/worker/testmain/_test/worker/testmain/main.a -I /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432/worker/_test -I /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432 -I /Users/goutham/CrazyAnalytics/EventServer/pkg/darwin-amd64 -complete _testmain.go]
2015/11/26 17:01:21 context.go:221: cd .; [/usr/local/go/pkg/tool/darwin_amd64/link -o /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432/worker/testmain/_test/.gb-link514049495 -L /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432/worker/_test -L /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432 -L /Users/goutham/CrazyAnalytics/EventServer/pkg/darwin-amd64 -buildmode exe /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432/worker/testmain/_test/worker/testmain/main.a]
worker
2015/11/26 17:01:23 test.go:51: test duration: 2.239024588s map[gc:439.635342ms link:1.185761797s]
2015/11/26 17:01:23 context.go:200: removing work directory: /var/folders/25/zwdt85b53vz1vqsjkxnx7wwr0000gn/T/gb946105432
```

**Comment by davecheney** [comment] 2015-11-26 11:38
Your test is run, see the line `worker`.

**Comment by Gouthamve** [comment] 2015-11-26 11:41
Hmm, okay. While I know its running (failures are showing up), I was expecting the following line that the go tool shows.
```
ok  	worker	0.522s
```

I guess, I am used to the go tool. Also please

**Comment by davecheney** [comment] 2015-11-26 12:27
@Gouthamve here are the current rules for the output (not debug) that gb prints.

You will get one line of output per package built or tested, if the operation is successful, the name of the package is printed _after_ the operation completes.

If the operation is a failure, you get the name of the package with a # before it, and any output from the command. 

I'm not totally happy with this scheme, especially for tests, see #438

**Comment by mowings** [comment] 2015-11-27 01:51
@davecheney -- I should be clear -- my actual tests run. If one fails, I get output. But basically -v doesn't work, so no output during a normal run with no failures, or timing info.

**Comment by davecheney** [comment] 2015-11-27 01:58
@mowings see #438

**Comment by davecheney** [comment] 2015-11-28 03:38
I believe this is now fixed. Closing for now. Please reopen if this is not fixed.

**Closed by davecheney** 2015-11-28 03:38 UTC

**Comment by liamstask** [comment] 2015-11-28 18:34
fixed for me. thank you.
