### ISSUE TITLE
Error: gb vendor fetch gopkg.in/mgo.v2

### ISSUE THREAD

**Issue by AlexanderChen1989** [constabulary/gb#145] opened 2015-05-27 02:16 UTC
FATAL command "fetch" failed: unknown repository type
FATAL command "vendor" failed: exit status 1

**Comment by davecheney** [comment] 2015-05-27 02:20
There is no support for vanity urls, yet. It's coming, soon.

Duplicate of #144

**Closed by davecheney** 2015-05-27 02:20 UTC
