### ISSUE TITLE
cgo not supported

### ISSUE THREAD

**Issue by fzerorubigd** [constabulary/gb#92] opened 2015-05-14 21:02 UTC
Creating this repo as an example of my problem https://github.com/fzerorubigd/gb-bug (The source is from the https://bitbucket.org/liamstask/goose ) 

`gb build` was failed with this message 
```
github.com/go-sql-driver/mysql
github.com/kylelemons/go-gypsy/yaml
github.com/lib/pq/oid
github.com/mattn/go-sqlite3
github.com/ziutek/mymysql/mysql
Usage: pack op file.a [name....]
Where op is one of cprtx optionally followed by v for verbose output.
For compatibility with old Go build environments the op string grc is
accepted as a synonym for c.

For more information, run
        godoc cmd/pack
# /usr/lib/go/pkg/tool/linux_amd64/pack r /tmp/gb128619612/github.com/mattn/go-sqlite3.a
github.com/lib/pq
github.com/ziutek/mymysql/native
FATAL command "build" failed: exit status 2
```

For reproduce, simply clone my repo https://bitbucket.org/liamstask/goose, (clone, submodule update) and then `gb build` but with `go get` every thing is fine.

**Comment by davecheney** [comment] 2015-05-14 21:25
Thanks, this is a duplicate of #12 as go-sqlite3 uses cgo and I don't have complete cgo support in place yet. It's coming real soon.

**Closed** 2015-05-18 12:32 UTC
Labels: bug
