### ISSUE TITLE
Some tools not working with gb's pkg directory layout

### ISSUE THREAD

**Issue by fenderle** [constabulary/gb#335] opened 2015-09-03 17:59 UTC
I just had a hard time chasing down a problem which showed up once I started using gb. Suddenly gotype didn't work and the gocode autocompletion also failed to find suggestions.

After some time of searching around I found that the problem is... - no it's not the GOPATH, but the way gb structures the pkg directory. After gb build I get

.../pkg/darwin-amd64/...

but all tools expect it to be

.../pkg/darwin_amd64/...

Once I renamed the directory everything worked again.

Using a dash (-) instead of an underscore (_) breaks integration with tools relying on the usual structure which go itself produces.

Is this a bug or am I just stupid? (Latter might be since I'm new to go)

Btw. I use go 1.5

**Comment by davecheney** [comment] 2015-09-03 22:17
You are not stupid, but this is also not a bug.

gb doesn't put .a files in the same places as the Go tool. This is for two reasons, 1. so it doesn't overwrite the output of the go tool when gb is used within a GOPATH. 2, to support cross compilation, conditional builds, and all the other tag like things that modify the context a build is in, the plan is to encode that information into the $PROJECT/pkg/.../ prefix.

Sadly, I don't have any more advice I can give to help make those tools work at this time.

Closing as this is mostly a dup of #202 and #314

**Closed by davecheney** 2015-09-03 22:17 UTC
