### ISSUE TITLE
gb vendor fails to fetch golang.org/x

### ISSUE THREAD

**Issue by utrack** [constabulary/gb#412] opened 2015-09-24 08:10 UTC
Steps to reproduce: try to fetch `golang.org/x/net/context`.
```
oldie% gb vendor fetch golang.org/x/net/context
FATAL command "fetch" failed: unable to determine remote metadata protocol: failed to access url "https://golang.org/x/net/context?go-get=1"
FATAL command "vendor" failed: exit status 1
```

**Comment by davecheney** [comment] 2015-09-24 10:58
@utrack I cannot reproduce this, can you please paste the output of
```
curl -v "https://golang.org/x/net/context?go-get=1"
```

**Comment by utrack** [comment] 2015-09-24 12:12
@davecheney sure,
```
oldie% curl -v "https://golang.org/x/net/context?go-get=1"
*   Trying 74.125.205.141...
* Connected to golang.org (74.125.205.141) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*        subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=misc-sni.google.com
*        start date: 2015-09-09 22:39:05 GMT
*        expire date: 2015-12-08 00:00:00 GMT
*        subjectAltName: golang.org matched
*        issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
*        SSL certificate verify ok.
> GET /x/net/context?go-get=1 HTTP/1.1
> Host: golang.org
> User-Agent: curl/7.44.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Date: Thu, 24 Sep 2015 12:11:23 GMT
< Server: Google Frontend
< Content-Length: 588
< Alternate-Protocol: 443:quic,p=1
< Alt-Svc: quic=":443"; p="1"; ma=604800
<
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="golang.org/x/net git https://go.googlesource.com/net">
<meta name="go-source" content="golang.org/x/net https://github.com/golang/net/ https://github.com/golang/net/tree/master{/dir} https://github.com/golang/net/blob/master{/dir}/{file}#L{line}">
<meta http-equiv="refresh" content="0; url=https://godoc.org/golang.org/x/net/context">
</head>
<body>
Nothing to see here; <a href="https://godoc.org/golang.org/x/net/context">move along</a>.
</body>
</html>
* Connection #0 to host golang.org left intact
```

**Comment by davecheney** [comment] 2015-09-24 12:14
Hmm, that's strange, I thought that it was an issue with a proxy.

**Comment by davecheney** [comment] 2015-11-12 10:26
I've had no other reports of this issue and have been unable to reproduce it myself. I'm sorry, but I don't know how to debug this issue.

I'm going to close this issue because there is nothing that I can do, I'm sorry for the inconvenience.

**Closed by davecheney** 2015-11-12 10:26 UTC

**Comment by wxk6b1203** [comment] 2018-08-03 01:38
I have an idea. If you are a Chinese user, it is possible because of Chinese government policy. You could test this by using raw `go get` to do this. Like: 
```bash
$ go get golang.org/x/sys/unix
```
Response is:
```
package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix" (https fetch: Get https://golang.org/x/sys/unix?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
```
If you use `proxychains`, it something like this: (this may not a common circumstance.)
```
package golang.org/x/crypto/ssh/terminal: unrecognized import path "golang.org/x/crypto/ssh/terminal" (https fetch: Get https://golang.org/x/crypto/ssh/terminal?go-get=1: dial tcp 224.0.0.1:443: connect: address family not supported by protocol family)
```
An alternative is, manually build the directory `golang.org/x/.........` and clone from github mirror.
