### ISSUE TITLE
Wrong project directory when running commands from <project>/vendor/src

### ISSUE THREAD

**Issue by PSG-Luna** [constabulary/gb#123] opened 2015-05-24 10:37 UTC
When running commands from the vendor/src directory, the project dir incorrectly gets determined to be <project>/vendor instead of <project>

**Comment by ChrisHines** [comment] 2015-05-24 13:18
I think this is the same as https://github.com/constabulary/gb/issues/66.

**Comment by davecheney** [comment] 2015-05-24 21:30
Duplicate of #66

**Closed by davecheney** 2015-05-24 21:30 UTC
