### ISSUE TITLE
gb vendor fetch has unhelpful error when pkg does not exist

### ISSUE THREAD

**Issue by pbx0** [constabulary/gb#508] opened 2015-12-22 05:07 UTC
```
$ gb vendor fetch github.com/docker/docker/pkg/units
FATAL: command "fetch" failed: lstat /tmp/gb-vendor-672541439/pkg/units: no such file or directory
FATAL: command "vendor" failed: exit status 1
```

The problem is that `github.com/docker/docker/pkg/units` no longer exists. The nit with gb is that the error message isn't all that helpful. I found this when I was recursively fetching dependancies for a kubernetes pkg.

**Comment by davecheney** [comment] 2015-12-25 17:01
Thank you for raising this issue. I plan to address this and several others very soon now by altering gb vendor to always vendor the entire repository unconditionally. Closing as duplicate of #475

**Closed by davecheney** 2015-12-25 17:01 UTC
