### ISSUE TITLE
Fetch unable to download repo

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [constabulary/gb#151] opened 2015-05-29 03:01 UTC
For some reason "gb vendor fetch speter.net/go/exp/math/dec/inf" fails to download speter.net/go/exp/math/dec/inf but go get speter.net/go/exp/math/dec/inf works fine.

**Comment by drewwells** [comment] 2015-05-29 03:04
Fetch the plain repo, paths inside repos are not supported yet.

**Comment by davecheney** [comment] 2015-05-29 03:05
Sorry, vanity imports are not supported yet

Duplicate of #144

**Closed by davecheney** 2015-05-29 03:05 UTC
