### ISSUE TITLE
structuring a project to build with gb but also to be friendly to `go get` et al

### ISSUE THREAD

**Issue by oconnor663** [constabulary/gb#284] opened 2015-07-31 15:29 UTC
It doesn't seem like it's possible to create a project that will build with `gb build` while *also* being friendly to people fetching my project with `go get`. Have I missed anything obvious?

I've created an example project at https://github.com/oconnor663/gbexample. It looks like this:

```
.
└── src
    └── github.com
        └── oconnor663
            └── gbexample
                ├── libexample
                │   └── libexample.go
                └── main.go
```

This builds and runs great with `gb build`. But if I try to fetch and build with the regular Go tool, I get failures:

```
go get github.com/oconnor663/gbexample      # gives an error, but still works
go install github.com/oconnor663/gbexample  # fails
```

That's because `main.go` imports `libexample` the way `gb` understands it, like this

```go
import  "github.com/oconnor663/gbexample/libexample"
```

Instead of the way standard `go build` sees it, which would've been this kind of gross path:

```go
import  "github.com/oconnor663/gbexample/src/github.com/libexample"
```

The workaround for regular `go build` seems to be to give it a special place in my `GOPATH` like this:

    export GOPATH="$GOPATH:[whatever]/gbexample"

That works in a pinch, but it means that you can't use the regular `go get` workflow to fetch dependencies for a project that takes my `libexample` as a dependency. You'd have to do that `GOPATH` hack, even if `libexample` was a second- or third-order dependency. Not very friendly to anyone who might want to use my code.

What would be *incredibly awesome* is if I were able to use symlinks to satisfy both build systems. Maybe like this:

```
.
├── libexample
│   └── libexample.go
├── main.go
└── src
    └── github.com
        └── oconnor663
            └── gbexample -> ../../..
```

Unfortunately neither `gb build` nor `go build` will traverse symlinks by design. (https://github.com/constabulary/gb/issues/91)

Is there another way to trick `gb` into building my otherwise-conventionally-structured project? If not, would it be possible to add a flag for this purpose. Maybe something like this?

    gb build --pretend-import-path-for-the-cwd=github.com/oconnor663/gbexample

Apologies for the wall of text :) Thanks for building `gb`!

**Comment by oconnor663** [comment] 2015-07-31 16:48
Or am I totally missing the point? Is the right way to do this to

1. use the standard project layout (*without* an internal `src/...` hierarchy),
2. clone the project at its normal spot in the `GOPATH`, and then
3. run `gb build` from the root of the `GOPATH` instead of the root of my project?

**Comment by davecheney** [comment] 2015-08-02 02:07
> It doesn't seem like it's possible to create a project that will build with gb build while also being friendly to people fetching my project with go get. Have I missed anything obvious?

I'm sorry for not replying in detail. You have not missed anything, gb projects are not go gettable. This is very much by design; if gb was just another tool that tried to work within the limitations of GOPATH and go get, what would be the compelling factor for people to use it ?

**Comment by davecheney** [comment] 2015-08-02 02:08
Sorry to close the issue, if you want to reopen it, or create a new issue with some actionable points, please do so.

**Closed by davecheney** 2015-08-02 02:07 UTC

**Comment by oconnor663** [comment] 2015-08-02 03:23
No worries. Out of curiosity, do you have any particular plans for making gb compatible with the vendoring features coming in go 1.5?

**Comment by davecheney** [comment] 2015-08-02 03:25
No, there are no plans. The go 1.5 vendor change is not applicable because gb does not use go get and gb projects are not go gettable.
