### ISSUE TITLE
GB can't crosscompile to 386 archs?

### ISSUE THREAD

**Issue by agonzalezro** [constabulary/gb#238] opened 2015-06-25 22:43 UTC
Hello,

I am trying to use this Dockerfile: https://github.com/agonzalezro/gb-cross/blob/master/Dockerfile to crosscompile `gb` projects.

It works completely fine with amd64 binaries. I managed to compile it for linux, darwin and freebsd. But every time that I try to compile for 386 archs, I get this error:

`/usr/src/go/pkg/tool/linux_amd64/6g: cannot use 6g with GOARCH=386`

Same container, with `go build` works. Example:

```
$ docker run -e GOOS=darwin -e GOARCH=386 -it agonzalezro/gb-cross /bin/bash
root@50e260d010b8:/tmp# gb build
cmd/test
/usr/src/go/pkg/tool/linux_amd64/6g: cannot use 6g with GOARCH=386
FATAL command "build" failed: # /usr/src/go/pkg/tool/linux_amd64/6g -p cmd/test -pack -o /tmp/gb272266032/cmd/test/main.a -I /tmp/gb272266032 -I /tmp/pkg/darwin/386 -complete src/cmd/test/main.go: exit status 1

root@50e260d010b8:/tmp# cd src/cmd/test/;go build;ls;cd -
main.go  test
/tmp

root@50e260d010b8:/tmp# file src/cmd/test/test
src/cmd/test/test: Mach-O i386 executable
```

As you can see, the second command works and a binary called `test` is created.

Do you think that this is a bug with `gb` itself? If not, please, do let me know.

**Comment by davecheney** [comment] 2015-06-25 22:52
Sorry, cross compilation is still on the backlog

**Comment by agonzalezro** [comment] 2015-06-26 13:00
I don't really have a lot of experience in cross compiling. But if you give me some advice I suppose that I could work in a PR to make this work. I would say that the key is here: https://github.com/constabulary/gb/blob/master/defaultcc.go & here: https://github.com/constabulary/gb/blob/master/defaultcc_bsd.go but I don't understand what else is needed.

**Comment by davecheney** [comment] 2015-06-27 04:33
If you don't have experience in this area, I would not advise you to start
in this area. This is not as simple as making sure GOOS and GOARCH are
passed down to the compiler.

**Comment by mholt** [comment] 2015-07-14 03:26
I know this isn't particularly helpful, but +1 for full cross-compilation support. Let me know if there's some way I can help.

**Comment by tianon** [comment] 2015-08-03 10:00
Isn't this technically a dupe of #31?

**Comment by davecheney** [comment] 2015-08-03 10:32
Duplicate of #31

**Closed by davecheney** 2015-08-03 10:32 UTC
