### ISSUE TITLE
CGO : gb failed when go succeed

### ISSUE THREAD

**Issue by fzerorubigd** [constabulary/gb#293] opened 2015-08-07 13:40 UTC
I have a simple c library and I want to use it with go. 
the cgo hint is like this : 
```// #cgo pkg-config: libzip libxml-2.0 libexslt```
the go build works fine, but I get error with gb : 

```
DEBUG project root "/home/develop/azmoona"
DEBUG args: [doxt]
DEBUG loadPackage: github.com/Sirupsen/logrus false (/home/develop/azmoona/vendor/src/github.com/Sirupsen/logrus)
DEBUG loadPackage: github.com/dchest/captcha false (/home/develop/azmoona/vendor/src/github.com/dchest/captcha)
DEBUG loadPackage: github.com/fzerorubigd/onion false (/home/develop/azmoona/vendor/src/github.com/fzerorubigd/onion)
DEBUG loadPackage: config false (/home/develop/azmoona/src/config)
DEBUG loadPackage: github.com/fzerorubigd/go-redmine false (/home/develop/azmoona/vendor/src/github.com/fzerorubigd/go-redmine)
DEBUG loadPackage: utils false (/home/develop/azmoona/src/utils)
DEBUG loadPackage: doxt true (/home/develop/azmoona/src/doxt)
DEBUG buildPackage: doxt
DEBUG buildPackage: utils
DEBUG buildPackage: config
DEBUG buildPackage: github.com/Sirupsen/logrus
DEBUG buildPackage: github.com/dchest/captcha
DEBUG buildPackage: github.com/fzerorubigd/onion
DEBUG buildPackage: github.com/fzerorubigd/go-redmine
DEBUG cd /home/develop/azmoona/src/doxt; [pkg-config --cflags libzip libxml-2.0 libexslt]
DEBUG cd /home/develop/azmoona/src/doxt; [pkg-config --libs libzip libxml-2.0 libexslt]
DEBUG cd /home/develop/azmoona/src/doxt; [/usr/local/go/pkg/tool/linux_amd64/cgo -objdir /tmp/gb799756233 -- -I /home/develop/azmoona/src/doxt ccode.go]
In file included from /home/develop/azmoona/src/doxt/ccode.go:92:0:
/usr/include/libxslt/transform.h:15:27: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
                           ^
compilation terminated.
DEBUG {main doxt /home/develop/azmoona/src/doxt} is a main package, not installing
DEBUG removing work directory: /tmp/gb799756233
DEBUG build duration: 28.02453ms map[]
FATAL command "build" failed: # /usr/local/go/pkg/tool/linux_amd64/cgo -objdir /tmp/gb799756233 -- -I /home/develop/azmoona/src/doxt ccode.go: exit status 2
```

I use a dockerized debian jessie container with go 1.4.2 and the current gb 107eaaa57b50166458992db6d66ee844d258986b 

I can not publish the source code here, but I can provide it to you if you need it.

**Comment by davecheney** [comment] 2015-08-08 08:08
Thanks. This is due to missing support for cgo packages that rely on
pkg-config.

**Comment by fzerorubigd** [comment] 2015-08-09 09:51
Is there any workaround to handle this?

On Sat, Aug 8, 2015 at 12:38 PM, Dave Cheney <notifications@github.com>
wrote:

> Thanks. This is due to missing support for cgo packages that rely on
> pkg-config.
> On 7 Aug 2015 11:40 pm, "fzerorubigd" <notifications@github.com> wrote:
>
> > I have a simple c library and I want to use it with go.
> > the cgo hint is like this :
> > // #cgo pkg-config: libzip libxml-2.0 libexslt
> > the go build works fine, but I get error with gb :
> >
> > DEBUG project root "/home/develop/azmoona"
> > DEBUG args: [doxt]
> > DEBUG loadPackage: github.com/Sirupsen/logrus false
> (/home/develop/azmoona/vendor/src/github.com/Sirupsen/logrus)
> > DEBUG loadPackage: github.com/dchest/captcha false
> (/home/develop/azmoona/vendor/src/github.com/dchest/captcha)
> > DEBUG loadPackage: github.com/fzerorubigd/onion false
> (/home/develop/azmoona/vendor/src/github.com/fzerorubigd/onion)
> > DEBUG loadPackage: config false (/home/develop/azmoona/src/config)
> > DEBUG loadPackage: github.com/fzerorubigd/go-redmine false
> (/home/develop/azmoona/vendor/src/github.com/fzerorubigd/go-redmine)
> > DEBUG loadPackage: utils false (/home/develop/azmoona/src/utils)
> > DEBUG loadPackage: doxt true (/home/develop/azmoona/src/doxt)
> > DEBUG buildPackage: doxt
> > DEBUG buildPackage: utils
> > DEBUG buildPackage: config
> > DEBUG buildPackage: github.com/Sirupsen/logrus
> > DEBUG buildPackage: github.com/dchest/captcha
> > DEBUG buildPackage: github.com/fzerorubigd/onion
> > DEBUG buildPackage: github.com/fzerorubigd/go-redmine
> > DEBUG cd /home/develop/azmoona/src/doxt; [pkg-config --cflags libzip
> libxml-2.0 libexslt]
> > DEBUG cd /home/develop/azmoona/src/doxt; [pkg-config --libs libzip
> libxml-2.0 libexslt]
> > DEBUG cd /home/develop/azmoona/src/doxt;
> [/usr/local/go/pkg/tool/linux_amd64/cgo -objdir /tmp/gb799756233 -- -I
> /home/develop/azmoona/src/doxt ccode.go]
> > In file included from /home/develop/azmoona/src/doxt/ccode.go:92:0:
> > /usr/include/libxslt/transform.h:15:27: fatal error: libxml/parser.h: No
> such file or directory
> > #include <libxml/parser.h>
> > ^
> > compilation terminated.
> > DEBUG {main doxt /home/develop/azmoona/src/doxt} is a main package, not
> installing
> > DEBUG removing work directory: /tmp/gb799756233
> > DEBUG build duration: 28.02453ms map[]
> > FATAL command "build" failed: # /usr/local/go/pkg/tool/linux_amd64/cgo
> -objdir /tmp/gb799756233 -- -I /home/develop/azmoona/src/doxt ccode.go:
> exit status 2
> >
> > I use a dockerized debian jessie container with go 1.4.2 and the current
> > gb 107eaaa
> > <
> https://github.com/constabulary/gb/commit/107eaaa57b50166458992db6d66ee844d258986b
> >
> >
> > I can not publish the source code here, but I can provide it to you if
> you
> > need it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/constabulary/gb/issues/293>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/constabulary/gb/issues/293#issuecomment-128929626>.
>



-- 
-----------------------------
http://fzero.rubi.gd

**Comment by davecheney** [comment] 2015-08-09 09:54
Not at the moment, but implementing this feature is high priority for me.

**Comment by davecheney** [comment] 2015-08-12 09:24
@fzerorubigd is the source of this application available so I can try to reproduce the problem ?

**Comment by fzerorubigd** [comment] 2015-08-12 13:28
Sorry for delay. I get the permit to publish this file. 
The Go code is created from two C source code (a c and a h file) for prevent another .so file. 

https://transfer.sh/1cwDYE/ccode.go

**Comment by davecheney** [comment] 2015-08-13 00:14
Thanks for that sample code, I've found a few bugs which will be fixed shortly.

**Comment by davecheney** [comment] 2015-08-13 01:52
@fzerorubigd #301 should help. I tried to reproduce your example but couldn't get the right packages installed on ubuntu.

**Comment by fzerorubigd** [comment] 2015-08-13 14:06
In debian I need to install `libzip-dev` , `libxslt1-dev` , `libxml2-dev` to build this one, Currently I have no Ubuntu machine to test it on that. 
I check with the current head, c1ed8e2185ccd8ea0b29cdc1330edb0dd34ccd78 and problem exists, the log is : 

```
gb build -v doxt
DEBUG project root "/home/azmoona/app_build"
DEBUG args: [doxt]
DEBUG loadPackage: github.com/Sirupsen/logrus false (/home/azmoona/app_build/vendor/src/github.com/Sirupsen/logrus)
DEBUG loadPackage: github.com/dchest/captcha false (/home/azmoona/app_build/vendor/src/github.com/dchest/captcha)
DEBUG loadPackage: github.com/fzerorubigd/onion false (/home/azmoona/app_build/vendor/src/github.com/fzerorubigd/onion)
DEBUG loadPackage: config false (/home/azmoona/app_build/src/config)
DEBUG loadPackage: github.com/fzerorubigd/go-redmine false (/home/azmoona/app_build/vendor/src/github.com/fzerorubigd/go-redmine)
DEBUG loadPackage: utils false (/home/azmoona/app_build/src/utils)
DEBUG loadPackage: doxt true (/home/azmoona/app_build/src/doxt)
DEBUG buildPackage: doxt
DEBUG buildPackage: utils
DEBUG buildPackage: config
DEBUG buildPackage: github.com/Sirupsen/logrus
DEBUG buildPackage: github.com/dchest/captcha 
DEBUG buildPackage: github.com/fzerorubigd/onion 
DEBUG buildPackage: github.com/fzerorubigd/go-redmine
DEBUG cd /home/azmoona/app_build/src/doxt; [pkg-config --cflags libzip libxml-2.0 libexslt]
DEBUG cd /home/azmoona/app_build/src/doxt; [pkg-config --libs libzip libxml-2.0 libexslt]
DEBUG cd /home/azmoona/app_build/src/doxt; [/usr/local/go/pkg/tool/linux_amd64/cgo -objdir /tmp/gb850509869 -- -I /home/azmoona/app_build/src/doxt ccode.go]
In file included from /home/azmoona/app_build/src/doxt/ccode.go:92:0:
/usr/include/libxslt/transform.h:15:27: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
                           ^
compilation terminated.
DEBUG removing work directory: /tmp/gb850509869
DEBUG build duration: 58.289322ms map[]
FATAL command "build" failed: # /usr/local/go/pkg/tool/linux_amd64/cgo -objdir /tmp/gb850509869 -- -I /home/azmoona/app_build/src/doxt ccode.go: exit status 2
```

And the go build log, with -x flag : 

```
WORK=/tmp/go-build066406305
mkdir -p $WORK/github.com/Sirupsen/logrus/_obj/
mkdir -p $WORK/github.com/Sirupsen/
cd /home/azmoona/app_build/vendor/src/github.com/Sirupsen/logrus
/usr/local/go/pkg/tool/linux_amd64/6g -o $WORK/github.com/Sirupsen/logrus.a -trimpath $WORK -p github.com/Sirupsen/logrus -complete -D _/home/azmoona/app_build/vendor/src/github.com/Sirupsen/logrus -I $WORK -pack ./entry.go ./exported.go ./formatter.go ./hooks.go ./json_formatter.go ./logger.go ./logrus.go ./terminal_linux.go ./terminal_notwindows.go ./text_formatter.go ./writer.go
mkdir -p $WORK/github.com/dchest/captcha/_obj/
mkdir -p $WORK/github.com/dchest/
cd /home/azmoona/app_build/vendor/src/github.com/dchest/captcha
/usr/local/go/pkg/tool/linux_amd64/6g -o $WORK/github.com/dchest/captcha.a -trimpath $WORK -p github.com/dchest/captcha -complete -D _/home/azmoona/app_build/vendor/src/github.com/dchest/captcha -I $WORK -pack ./audio.go ./captcha.go ./font.go ./image.go ./random.go ./server.go ./siprng.go ./sounds.go ./store.go
mkdir -p $WORK/github.com/fzerorubigd/onion/_obj/
mkdir -p $WORK/github.com/fzerorubigd/
cd /home/azmoona/app_build/vendor/src/github.com/fzerorubigd/onion
/usr/local/go/pkg/tool/linux_amd64/6g -o $WORK/github.com/fzerorubigd/onion.a -trimpath $WORK -p github.com/fzerorubigd/onion -complete -D _/home/azmoona/app_build/vendor/src/github.com/fzerorubigd/onion -I $WORK -pack ./doc.go ./env_layer.go ./file_layer.go ./folder_layer.go ./json_loader.go ./onion.go
mkdir -p $WORK/github.com/fzerorubigd/go-redmine/_obj/
cd /home/azmoona/app_build/vendor/src/github.com/fzerorubigd/go-redmine
/usr/local/go/pkg/tool/linux_amd64/6g -o $WORK/github.com/fzerorubigd/go-redmine.a -trimpath $WORK -p github.com/fzerorubigd/go-redmine -complete -D _/home/azmoona/app_build/vendor/src/github.com/fzerorubigd/go-redmine -I $WORK -pack ./client.go ./issue.go ./issue_categories.go ./issue_priorities.go ./issue_relations.go ./issue_statuses.go ./membership.go ./news.go ./project.go ./roles.go ./time_entries.go ./time_entry_activities.go ./trackers.go ./user.go
mkdir -p $WORK/config/_obj/
mkdir -p $WORK/
cd /home/azmoona/app_build/src/config
/usr/local/go/pkg/tool/linux_amd64/6g -o $WORK/config.a -trimpath $WORK -p config -complete -D _/home/azmoona/app_build/src/config -I $WORK -I /home/azmoona/app_build/vendor/pkg/linux_amd64 -pack ./config.go
mkdir -p $WORK/utils/_obj/
cd /home/azmoona/app_build/src/utils
/usr/local/go/pkg/tool/linux_amd64/6g -o $WORK/utils.a -trimpath $WORK -p utils -complete -D _/home/azmoona/app_build/src/utils -I $WORK -I /home/azmoona/app_build/pkg/linux_amd64 -I /home/azmoona/app_build/vendor/pkg/linux_amd64 -pack ./fautils.go ./files.go ./mine.go ./random.go ./string.go ./time.go
mkdir -p $WORK/doxt/_obj/
mkdir -p $WORK/doxt/_obj/exe/
cd /home/azmoona/app_build/src/doxt
pkg-config --cflags libzip libxml-2.0 libexslt
pkg-config --libs libzip libxml-2.0 libexslt
CGO_LDFLAGS="-g" "-O2" "-lzip" "-lz" "-lexslt" "-lxslt" "-lxml2" /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/doxt/_obj/ -- -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I $WORK/doxt/_obj/ ccode.go
/usr/local/go/pkg/tool/linux_amd64/6c -F -V -w -trimpath $WORK -I $WORK/doxt/_obj/ -I /usr/local/go/pkg/linux_amd64 -o $WORK/doxt/_obj/_cgo_defun.6 -D GOOS_linux -D GOARCH_amd64 $WORK/doxt/_obj/_cgo_defun.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -print-libgcc-file-name
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I $WORK/doxt/_obj/ -g -O2 -o $WORK/doxt/_obj/_cgo_main.o -c $WORK/doxt/_obj/_cgo_main.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I $WORK/doxt/_obj/ -g -O2 -o $WORK/doxt/_obj/_cgo_export.o -c $WORK/doxt/_obj/_cgo_export.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/libxml2 -I $WORK/doxt/_obj/ -g -O2 -o $WORK/doxt/_obj/ccode.cgo2.o -c $WORK/doxt/_obj/ccode.cgo2.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/doxt/_obj/_cgo_.o $WORK/doxt/_obj/_cgo_main.o $WORK/doxt/_obj/_cgo_export.o $WORK/doxt/_obj/ccode.cgo2.o -g -O2 -lzip -lz -lexslt -lxslt -lxml2
/usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/doxt/_obj/ -dynimport $WORK/doxt/_obj/_cgo_.o -dynout $WORK/doxt/_obj/_cgo_import.c
/usr/local/go/pkg/tool/linux_amd64/6c -F -V -w -trimpath $WORK -I $WORK/doxt/_obj/ -I /usr/local/go/pkg/linux_amd64 -o $WORK/doxt/_obj/_cgo_import.6 -D GOOS_linux -D GOARCH_amd64 $WORK/doxt/_obj/_cgo_import.c
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -o $WORK/doxt/_obj/_all.o $WORK/doxt/_obj/_cgo_export.o $WORK/doxt/_obj/ccode.cgo2.o -g -O2 -Wl,-r -nostdlib /usr/lib/gcc/x86_64-linux-gnu/4.9/libgcc.a -Wl,--build-id=none
/usr/local/go/pkg/tool/linux_amd64/6g -o $WORK/doxt.a -trimpath $WORK -p doxt -D _/home/azmoona/app_build/src/doxt -I $WORK -I /home/azmoona/app_build/pkg/linux_amd64 -pack ./main.go $WORK/doxt/_obj/_cgo_gotypes.go $WORK/doxt/_obj/ccode.cgo1.go
pack r $WORK/doxt.a $WORK/doxt/_obj/_cgo_import.6 $WORK/doxt/_obj/_cgo_defun.6 $WORK/doxt/_obj/_all.o # internal
cd .
/usr/local/go/pkg/tool/linux_amd64/6l -o $WORK/doxt/_obj/exe/a.out -L $WORK -L /home/azmoona/app_build/vendor/pkg/linux_amd64 -L /home/azmoona/app_build/pkg/linux_amd64 -extld=gcc $WORK/doxt.a
cp $WORK/doxt/_obj/exe/a.out doxt
```

Hope this help.

**Comment by davecheney** [comment] 2015-08-14 04:00
Fixed in #304

**Closed by davecheney** 2015-08-14 04:01 UTC

**Comment by fzerorubigd** [comment] 2015-08-14 08:21
Thank you! it is fixed.

**Comment by davecheney** [comment] 2015-08-14 08:28
Thanks for confirming. I think I squashed a lot of bugs with one commit today.
